In [2]:
import numpy as np 
import pandas as pd

df=pd.read_csv("C:\\Users\\Ghansham Belekar\\OneDrive\\Desktop\\returns_sustainability_dataset.csv")
display(df)

,Order_ID,Product_ID,User_ID,Order_Date,Product_Category,Product_Price,Order_Quantity,Discount_Applied,Shipping_Method,Payment_Method,...,Return_Status,Return_Reason,Days_to_Return,Order_Value,Return_Cost,Profit_Loss,CO2_Emissions,Packaging_Waste,CO2_Saved,Waste_Avoided
0,ORD00000,PROD0169,USER0195,2022-01-14,Clothing,1720.71,2,30.46,Next-Day,Wallet,...,Not Returned,No Return,0,2393.163468,0,2393.163468,2.0,0.4,2.0,0.4
1,ORD00001,PROD0318,USER1469,2022-01-03,Toys,744.06,5,29.62,Next-Day,Wallet,...,Returned,Size Issue,12,2618.347140,200,2418.347140,2.0,1.0,0.0,0.0
2,ORD00002,PROD0427,USER1812,2025-03-16,Clothing,983.68,5,47.80,Express,Wallet,...,Not Returned,No Return,0,2567.404800,0,2567.404800,1.5,1.0,1.5,1.0
3,ORD00003,PROD0323,USER1274,2024-11-06,Books,1855.65,2,2.90,Express,COD,...,Not Returned,No Return,0,3603.672300,0,3603.672300,1.5,0.4,1.5,0.4
4,ORD00004,PROD0325,USER0551,2023-06-07,Home Appliances,1770.97,5,44.42,Express,COD,...,Returned,Size Issue,11,4921.525630,200,4721.525630,1.5,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,ORD04995,PROD0122,USER0058,2024-08-12,Clothing,1729.90,5,4.50,Next-Day,Debit Card,...,Not Returned,No Return,0,8260.272500,0,8260.272500,2.0,1.0,2.0,1.0
4996,ORD04996,PROD0387,USER1666,2024-08-25,Books,1254.75,4,32.73,Express,COD,...,Not Returned,No Return,0,3376.281300,0,3376.281300,1.5,0.8,1.5,0.8
4997,ORD04997,PROD0072,USER0298,2023-11-15,Clothing,1183.28,3,31.03,Standard,Debit Card,...,Not Returned,No Return,0,2448.324648,0,2448.324648,1.0,0.6,1.0,0.6
4998,ORD04998,PROD0362,USER0968,2024-01-03,Books,1761.47,4,11.30,Express,Wallet,...,Not Returned,No Return,0,6249.695560,0,6249.695560,1.5,0.8,1.5,0.8
4999,ORD04999,PROD0265,USER0730,2025-08-08,Electronics,1975.01,1,39.85,Express,Wallet,...,Not Returned,No Return,0,1187.968515,0,1187.968515,1.5,0.2,1.5,0.2

In [5]:
df.head()

,Order_ID,Product_ID,User_ID,Order_Date,Product_Category,Product_Price,Order_Quantity,Discount_Applied,Shipping_Method,Payment_Method,...,Return_Status,Return_Reason,Days_to_Return,Order_Value,Return_Cost,Profit_Loss,CO2_Emissions,Packaging_Waste,CO2_Saved,Waste_Avoided
0,ORD00000,PROD0169,USER0195,2022-01-14,Clothing,1720.71,2,30.46,Next-Day,Wallet,...,Not Returned,No Return,0,2393.163468,0,2393.163468,2.0,0.4,2.0,0.4
1,ORD00001,PROD0318,USER1469,2022-01-03,Toys,744.06,5,29.62,Next-Day,Wallet,...,Returned,Size Issue,12,2618.347140,200,2418.347140,2.0,1.0,0.0,0.0
2,ORD00002,PROD0427,USER1812,2025-03-16,Clothing,983.68,5,47.80,Express,Wallet,...,Not Returned,No Return,0,2567.404800,0,2567.404800,1.5,1.0,1.5,1.0
3,ORD00003,PROD0323,USER1274,2024-11-06,Books,1855.65,2,2.90,Express,COD,...,Not Returned,No Return,0,3603.672300,0,3603.672300,1.5,0.4,1.5,0.4
4,ORD00004,PROD0325,USER0551,2023-06-07,Home Appliances,1770.97,5,44.42,Express,COD,...,Returned,Size Issue,11,4921.525630,200,4721.525630,1.5,1.0,0.0,0.0

In [6]:
df.shape

(5000, 23)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5000 non-null   object
 1   Product_ID        5000 non-null   object
 2   User_ID           5000 non-null   object
 3   Order_Date        5000 non-null   object
 4   Product_Category  5000 non-null   object
 5   Product_Price     5000 non-null   float64
 6   Order_Quantity    5000 non-null   int64
 7   Discount_Applied  5000 non-null   float64
 8   Shipping_Method   5000 non-null   object
 9   Payment_Method    5000 non-null   object
 10  User_Age          5000 non-null   int64
 11  User_Gender       5000 non-null   object
 12  User_Location     5000 non-null   object
 13  Return_Status     5000 non-null   object
 14  Return_Reason     5000 non-null   object
 15  Days_to_Return    5000 non-null   int64
 16  Order_Value       5000 non-null   float64
 17  Return_Cost       5000 non-null   int64
 18  Profit_Loss       5000 non-null   float64
 19  CO2_Emissions     5000 non-null   float64
 20  Packaging_Waste   5000 non-null   float64
 21  CO2_Saved         5000 non-null   float64
 22  Waste_Avoided     5000 non-null   float64
dtypes: float64(8), int64(4), object(11)
memory usage: 898.6+ KB

In [8]:
df.isnull().sum()

Order_ID            0
Product_ID          0
User_ID             0
Order_Date          0
Product_Category    0
Product_Price       0
Order_Quantity      0
Discount_Applied    0
Shipping_Method     0
Payment_Method      0
User_Age            0
User_Gender         0
User_Location       0
Return_Status       0
Return_Reason       0
Days_to_Return      0
Order_Value         0
Return_Cost         0
Profit_Loss         0
CO2_Emissions       0
Packaging_Waste     0
CO2_Saved           0
Waste_Avoided       0
dtype: int64

In [12]:
df.describe()

,Product_Price,Order_Quantity,Discount_Applied,User_Age,Days_to_Return,Order_Value,Return_Cost,Profit_Loss,CO2_Emissions,Packaging_Waste,CO2_Saved,Waste_Avoided
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000
mean,1054.294740,2.997600,25.011476,41.551800,9.204200,2366.996469,58.000000,2308.996469,1.500100,0.599520,1.066600,0.42668
std,548.560406,1.400709,14.430681,13.890195,16.753156,1834.851991,90.761487,1838.461511,0.410346,0.280142,0.764448,0.36150
min,100.090000,1.000000,0.000000,18.000000,0.000000,52.165727,0.000000,-147.834273,1.000000,0.200000,0.000000,0.00000
25%,580.937500,2.000000,12.827500,30.000000,0.000000,928.078449,0.000000,863.905130,1.000000,0.400000,0.000000,0.00000
50%,1044.850000,3.000000,25.020000,42.000000,0.000000,1864.584054,0.000000,1808.077845,1.500000,0.600000,1.000000,0.40000
75%,1530.835000,4.000000,37.380000,54.000000,12.000000,3382.309799,200.000000,3345.675860,2.000000,0.800000,1.500000,0.80000
max,1999.800000,5.000000,50.000000,65.000000,60.000000,9827.017200,200.000000,9827.017200,2.000000,1.000000,2.000000,1.00000

In [13]:
df.describe(include='object')

,Order_ID,Product_ID,User_ID,Order_Date,Product_Category,Shipping_Method,Payment_Method,User_Gender,User_Location,Return_Status,Return_Reason
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,5000,500,1858,1309,5,3,4,2,100,2,5
top,ORD00000,PROD0176,USER0780,2023-01-19,Clothing,Next-Day,Debit Card,Female,City35,Not Returned,No Return
freq,1,22,9,11,1766,1684,1277,2576,72,3550,3550

In [15]:
print("Total Duplicate Rows:", df.duplicated().sum())

Total Duplicate Rows: 0

In [16]:
df["Order_ID"].nunique()

5000

In [17]:
df['User_ID'].nunique()

1858

In [21]:
 df["Order_Date"] =pd.to_datetime(df["Order_Date"],errors="coerce")

In [24]:
df["Return_Status"].value_counts()

Return_Status
Not Returned    3550
Returned        1450
Name: count, dtype: int64

In [27]:
return_percentage = df["Return_Status"].value_counts(normalize="True") * 100

print(return_percentage)

Return_Status
Not Returned    71.0
Returned        29.0
Name: proportion, dtype: float64

In [32]:
overall_return_rate = (
    df["Return_Status"].eq("Returned").mean() * 100
)

print(f"Overall Return Rate: {overall_return_rate:.2f}%")

Overall Return Rate: 29.00%

In [35]:
df["Product_Category"].value_counts()

Product_Category
Clothing           1766
Electronics        1244
Books               762
Toys                752
Home Appliances     476
Name: count, dtype: int64

In [36]:
df["Shipping_Method"].value_counts()

Shipping_Method
Next-Day    1684
Standard    1683
Express     1633
Name: count, dtype: int64

In [37]:
df["Payment_Method"].value_counts()

Payment_Method
Debit Card     1277
Wallet         1275
Credit Card    1235
COD            1213
Name: count, dtype: int64

In [39]:
df["Discount_Applied"].describe()

count    5000.000000
mean       25.011476
std        14.430681
min         0.000000
25%        12.827500
50%        25.020000
75%        37.380000
max        50.000000
Name: Discount_Applied, dtype: float64

In [40]:
df["Product_Price"].describe()

count    5000.000000
mean     1054.294740
std       548.560406
min       100.090000
25%       580.937500
50%      1044.850000
75%      1530.835000
max      1999.800000
Name: Product_Price, dtype: float64

In [41]:
df["CO2_Emissions"].describe()

count    5000.000000
mean        1.500100
std         0.410346
min         1.000000
25%         1.000000
50%         1.500000
75%         2.000000
max         2.000000
Name: CO2_Emissions, dtype: float64

In [42]:
df["Packaging_Waste"].describe()

count    5000.000000
mean        0.599520
std         0.280142
min         0.200000
25%         0.400000
50%         0.600000
75%         0.800000
max         1.000000
Name: Packaging_Waste, dtype: float64

In [43]:
df["CO2_Saved"].describe()

count    5000.000000
mean        1.066600
std         0.764448
min         0.000000
25%         0.000000
50%         1.000000
75%         1.500000
max         2.000000
Name: CO2_Saved, dtype: float64

In [47]:
category_total = df.groupby("Product_Category").size()


category_returned = (
    df[df["Return_Status"] == "Returned"]
    .groupby("Product_Category")
    .size()
)


category_return_rate = (
    category_returned / category_total * 100
).fillna(0)

In [48]:
category_analysis = pd.DataFrame({
    "Total_Orders": category_total,
    "Returned_Orders": category_returned,
    "Return_Rate (%)": category_return_rate
}).fillna(0)


print(category_analysis)

                  Total_Orders  Returned_Orders  Return_Rate (%)
Product_Category
Books                      762              172        22.572178
Clothing                  1766              661        37.429219
Electronics               1244              314        25.241158
Home Appliances            476              122        25.630252
Toys                       752              181        24.069149